FROM python:3.12

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y 

# Copy requirements and install dependencies
RUN pip install chainlit pydantic==2.10.1 httpx 

# Copy application code
COPY  frontend /app/frontend
COPY frontend/chainlit.md /app/chainlit.md

# Expose Chainlit port
EXPOSE 8501

# Run Chainlit
CMD ["chainlit", "run", "frontend/chainlit.py", "--host", "0.0.0.0", "--port", "8501"]