version: '3.12'
services:
  travis-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: travis-backend:latest
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}